    
trigger:
  branches:
    include:
    - master

variables:
  helmVersion: '2.14.1'
  kubectlVersion: v1.12.1
  nodeVersionSpec: 10.x

stages:
  - template: ../../../../pipeline-template.yml
    parameters:
      linuxAgentPool: 'ubuntu-latest'
      windowsAgentPool: 'windows-latest'
      buildType: 'npm'
      projectName: 'mydrive-user'
      initSteps: []
      docker: true
      helm: true
      imageName: 'mydrive-user'
      helmCharts: charts
      codeRootDir: docs/demo/npm
      deployType: 'helm-native'
      PR: {
        enabled: false,
        gate: true,
        credscan: true,
        codescan: true,
        vulnerabilitiesscan: true
      }
      CI: {
        enabled: true,
        azureContainerRegistry: 'artifacts-repo', 
        azureSubscription: 'azure-service-connection',
        azureContainerRegistryName: 'orgsharedregistry',
        scan: true,
        gate: true,
      }
      AUTOMATION: {
        enabled: true,
        azureSubscription: 'azure-service-connection', 
        azureContainerRegistry: 'artifacts-repo',
        azureContainerRegistryName: 'orgsharedregistry',
        environmentNamespace: 'Automation.automation', 
        namespace: 'automation',
        upgradeParameters: '--set repository=orgsharedregistry.azurecr.io/mydrive-user --set tag=$(Build.BuildId) --set name=mydrive-user', 
        gate: true     
      }
      FUNCTIONAL: {
        enabled: true,
        azureSubscription: 'azure-service-connection', 
        azureContainerRegistry: 'artifacts-repo',
        azureContainerRegistryName: 'orgsharedregistry',
        environmentNamespace: 'Functional.functional', 
        namespace: 'functional',
        upgradeParameters: '--set repository=orgsharedregistry.azurecr.io/mydrive-user --set tag=$(Build.BuildId) --set name=mydrive-user',
        testType: 'galing',
        gatlingScenario: '',
        gate: true,
      }
      NONFUNCTIONAL: {
        enabled: true,
        azureSubscription: 'azure-service-connection', 
        azureContainerRegistry: 'artifacts-repo',
        azureContainerRegistryName: 'orgsharedregistry',
        environmentNamespace: 'NonFunctional.nonfunctional', 
        namespace: 'nonfunctional',
        upgradeParameters: '--set repository=orgsharedregistry.azurecr.io/mydrive-user --set tag=$(Build.BuildId) --set name=mydrive-user',
        gate: true
      }